// ChessOS — Master Games Study Library

export interface MoveDetails {
  move: string;
  eval?: string;
  idea?: string;
  motif?: string;
  comment: string;
  alternatives?: string[];
}

export interface MasterGame {
  id: string;
  white: string;
  black: string;
  event: string;
  date: string;
  result: string;
  description: string;
  initialFen: string;
  moves: MoveDetails[];
}

export const MASTER_GAMES: MasterGame[] = [
  {
    id: 'morphy_opera',
    white: 'Paul Morphy',
    black: 'Duke Karl / Count Isouard',
    event: 'Paris Opera House',
    date: '1858',
    result: '1-0',
    description: 'The most famous game in chess history. Morphy demonstrates the power of rapid development, open lines, and a spectacular mating sacrifice.',
    initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    moves: [
      { move: 'e4', eval: '+0.3', idea: 'Control Center', motif: 'Open Lines', comment: 'Morphy opens the game by claiming space in the center and preparing development of the light-squared bishop.' },
      { move: 'e5', eval: '+0.3', idea: 'Defend Center', motif: 'Symmetrical', comment: 'Black responds symmetrically, staking their own claim to the center.' },
      { move: 'Nf3', eval: '+0.4', idea: 'Develop & Attack', motif: 'Tempo', comment: 'Developing the knight to its most active square, attacking the e5 pawn and preparing castling.' },
      { move: 'd6', eval: '+0.6', idea: 'Philidor Defense', motif: 'Passive Def', comment: 'The Philidor Defense. It defends the e5 pawn but restricts the dark-squared bishop.' },
      { move: 'd4', eval: '+0.7', idea: 'Center Breakthrough', motif: 'Space', comment: 'Morphy immediately strikes in the center, challenging Black\'s pawn on e5.' },
      { move: 'Bg4', eval: '+1.1', idea: 'Counter Threat', motif: 'Pin', comment: 'Black pins the f3 knight. However, this is considered slightly passive compared to dxe5.' },
      { move: 'dxe5', eval: '+1.2', idea: 'Exploit Pin', motif: 'Tactics', comment: 'Morphy exchanges pawns. Black cannot recapture immediately without losing the queen.' },
      { move: 'Bxf3', eval: '+1.3', idea: 'Eliminate Defender', motif: 'Trade', comment: 'Forced to trade the bishop to avoid losing material, giving up the bishop pair.' },
      { move: 'Qxf3', eval: '+1.3', idea: 'Active Queen', motif: 'Development', comment: 'Morphy recaptures with the queen, keeping active pressure and development leads.' },
      { move: 'dxe5', eval: '+1.4', idea: 'Recapture Pawn', motif: 'Material Equal', comment: 'Black recaptures the pawn on e5, keeping material balance but lagging in development.' },
      { move: 'Bc4', eval: '+1.8', idea: 'Mating Threat', motif: 'Weak f7', comment: 'Morphy develops the bishop with a direct threat of checkmate on f7.' },
      { move: 'Nf6', eval: '+1.8', idea: 'Block Mate', motif: 'Defense', comment: 'Black blocks the mating line with the knight, developing a piece.' },
      { move: 'Qb3', eval: '+2.3', idea: 'Double Attack', motif: 'Weak b7 & f7', comment: 'Morphy creates a double attack on b7 and f7. A classic tactical concept.' },
      { move: 'Qe7', eval: '+2.3', idea: 'Defend f7', motif: 'Defensive Move', comment: 'Black defends the f7 pawn, but now the b7 pawn is undefended.' },
      { move: 'Nc3', eval: '+2.7', idea: 'Rapid Development', motif: 'Prophylaxis', comment: 'Instead of greedily taking on b7, Morphy prioritizes development. Dynamic play!' },
      { move: 'c6', eval: '+2.8', idea: 'Defend b7', motif: 'Pawn Wall', comment: 'Black guards the b5 and d5 squares, hoping to stabilize the position.' },
      { move: 'Bg5', eval: '+3.2', idea: 'Absolute Pin', motif: 'Pin', comment: 'Morphy pins the f6 knight to the queen, locking down Black\'s defenses.' },
      { move: 'b5', eval: '+4.1', idea: 'Chase Bishop', motif: 'Weakening', comment: 'Black tries to drive away the c4 bishop, but this creates massive weaknesses in their structure.' },
      { move: 'Nxb5', eval: '+4.5', idea: 'Knight Sacrifice', motif: 'Breakthrough', comment: 'Morphy sacrifices the knight for two pawns to blast open the lines to the black king!' },
      { move: 'cxb5', eval: '+4.5', idea: 'Accept Sacrifice', motif: 'Material Gain', comment: 'Black accepts the sacrifice, but their king remains stranded in the center.' },
      { move: 'Bxb5+', eval: '+4.8', idea: 'Check & Attack', motif: 'Tempo', comment: 'Morphy recaptures with check, developing with force.' },
      { move: 'Nbd7', eval: '+4.8', idea: 'Block Check', motif: 'Defense', comment: 'Black blocks with the knight, but this piece is now pinned absolutely.' },
      { move: 'O-O-O', eval: '+5.5', idea: 'Castle & Attack', motif: 'King Safety', comment: 'Morphy castles queenside, bringing the rook directly into the attack on the pinned d7 knight!' },
      { move: 'Rd8', eval: '+5.5', idea: 'Defend Pinned Piece', motif: 'Defense', comment: 'Black defends the d7 knight with the rook. All black pieces are tied down.' },
      { move: 'Rxd7', eval: '+6.8', idea: 'Rook Sacrifice', motif: 'Deflection', comment: 'Morphy sacrifices the rook to remove the defender of the d7 square!' },
      { move: 'Rxd7', eval: '+6.8', idea: 'Recapture Rook', motif: 'Defense', comment: 'Black recaptures with the rook, which is now also pinned.' },
      { move: 'Rd1', eval: '+7.5', idea: 'Bring Last Reserve', motif: 'Attack', comment: 'Morphy brings his final piece, the h1 rook, to d1. Unbelievable coordination!' },
      { move: 'Qe6', eval: '+8.2', idea: 'Offer Queen Trade', motif: 'Desperation', comment: 'Black offers a queen trade, hoping to relieve the pressure, but it is too late.' },
      { move: 'Bxd7+', eval: '+12.0', idea: 'Check & Win', motif: 'Elimination', comment: 'Morphy exchanges on d7, bringing the mate sequence to its climax.' },
      { move: 'Nxd7', eval: '+12.0', idea: 'Recapture Knight', motif: 'Defense', comment: 'Black recaptures with the knight, leaving the back rank vulnerable.' },
      { move: 'Qb8+', eval: '+Mate', idea: 'Queen Sacrifice', motif: 'Decoy/Attraction', comment: 'Morphy sacrifices the queen! This attracts the d7 knight to b8, leaving d8 open.' },
      { move: 'Nxb8', eval: '+Mate', idea: 'Accept Queen Sacrifice', motif: 'Forced', comment: 'Forced recapture. The b8 square is now blocked by Black\'s own knight.' },
      { move: 'Rd8#', eval: '+Mate', idea: 'Mating Blow', motif: 'Back Rank Mate', comment: 'Checkmate! The lone rook delivers the final blow, supported by the bishop. Masterpiece.' }
    ]
  },
  {
    id: 'fischer_byrne',
    white: 'Donald Byrne',
    black: 'Bobby Fischer',
    event: 'Rosenwald Memorial',
    date: '1956',
    result: '0-1',
    description: 'The "Game of the Century". A 13-year-old Bobby Fischer sacrifices his queen for a winning attack, showing depth of calculation far beyond his years.',
    initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    moves: [
      { move: 'Nf3', eval: '+0.2', idea: 'Reti Opening', comment: 'Byrne opens with the flexible knight development, keeping options open.' },
      { move: 'Nf6', eval: '+0.2', comment: 'Fischer responds symmetrically.' },
      { move: 'c4', eval: '+0.2', comment: 'Preparing queenside expansion.' },
      { move: 'g6', eval: '+0.3', comment: 'Preparing to fianchetto the king\'s bishop.' },
      { move: 'Nc3', eval: '+0.3', comment: 'Developing the knight to control the center.' },
      { move: 'Bg7', eval: '+0.3', comment: 'Fianchetto completed.' },
      { move: 'd4', eval: '+0.3', comment: 'Byrne stakes full claim to the center.' },
      { move: 'O-O', eval: '+0.4', comment: 'Fischer secures king safety early.' },
      { move: 'Bf4', eval: '+0.4', comment: 'Active bishop development.' },
      { move: 'd5', eval: '+0.5', comment: 'Fischer challenges White\'s center.' },
      { move: 'Qb3', eval: '+0.5', comment: 'Attacking d5 and b7.' },
      { move: 'dxc4', eval: '+0.6', comment: 'Releasing center tension.' },
      { move: 'Qxc4', eval: '+0.6', comment: 'Recapturing with the queen.' },
      { move: 'c6', eval: '+0.6', comment: 'Solidifying the d5 square.' },
      { move: 'e4', eval: '+0.5', comment: 'Byrne establishes a broad pawn center.' },
      { move: 'Nbd7', eval: '+0.6', comment: 'Fischer prepares to jump to b6.' },
      { move: 'Rd1', eval: '+0.7', comment: 'X-raying the d-file.' },
      { move: 'Nb6', eval: '+0.5', comment: 'Chasing the white queen.' },
      { move: 'Qc5', eval: '+0.8', comment: 'Byrne keeps queen active.' },
      { move: 'Bg4', eval: '+0.6', comment: 'Pinning the knight on f3.' },
      { move: 'Bg5', eval: '+0.8', comment: 'Developing the bishop.' },
      { move: 'Na4', eval: '-0.3', idea: 'Knight Jump', comment: 'Fischer begins a brilliant counterplay, sacrificing on c3.' },
      { move: 'Qa3', eval: '-0.3', comment: 'Moving queen out of attack.' },
      { move: 'Nxc3', eval: '-0.4', comment: 'Fischer captures the knight, damaging White\'s pawn structure.' },
      { move: 'bxc3', eval: '-0.4', comment: 'Recapturing.' },
      { move: 'Nxe4', eval: '-0.7', comment: 'Grabbing the central e4 pawn with threats.' },
      { move: 'Bxe7', eval: '-0.9', comment: 'Byrne attacks the black queen.' },
      { move: 'Qb6', eval: '-0.8', comment: 'Retreating queen while eyeing b2.' },
      { move: 'Bc4', eval: '-1.2', comment: 'Active bishop development.' },
      { move: 'Nxc3', eval: '-1.4', comment: 'Fischer captures c3, setting up a magnificent combination.' },
      { move: 'Bc5', eval: '-1.5', comment: 'Byrne attacks the queen, thinking he won a piece.' },
      { move: 'Rfe8+', eval: '-2.1', comment: 'Fischer brings the rook in with check.' },
      { move: 'Kf1', eval: '-2.1', comment: 'Byrne\'s king is forced to move.' },
      { move: 'Be6', eval: '-4.6', idea: 'Queen Sacrifice', motif: 'Brilliancy', comment: 'Fischer sacrifices his queen! A historical move. If White takes the queen, Fischer gets a devastating attack.' },
      { move: 'Bxb6', eval: '-4.8', comment: 'Byrne accepts the queen sacrifice, stepping into checkmate nets.' },
      { move: 'Bxc4+', eval: '-5.2', comment: 'Fischer checks and regains material step by step.' },
      { move: 'Kg1', eval: '-5.2', comment: 'King retreats.' },
      { move: 'Ne2+', eval: '-5.5', comment: 'Double check threat with knight.' },
      { move: 'Kf1', eval: '-5.5', comment: 'Forced.' },
      { move: 'Nxd4+', eval: '-5.8', comment: 'Knight capture with discovered check.' },
      { move: 'Kg1', eval: '-5.8', comment: 'Forced retreat.' },
      { move: 'Ne2+', eval: '-5.8', comment: 'Windmill check starts.' },
      { move: 'Kf1', eval: '-5.8', comment: 'Forced.' },
      { move: 'Nc3+', eval: '-6.2', comment: 'Discovered check again.' },
      { move: 'Kg1', eval: '-6.2', comment: 'Forced.' },
      { move: 'axb6', eval: '-6.5', comment: 'Fischer captures the bishop, winning material.' },
      { move: 'Qb4', eval: '-7.0', comment: 'Queen is target.' },
      { move: 'Ra4', eval: '-7.2', comment: 'Protecting and attacking.' },
      { move: 'Qxb3', eval: '-7.2', comment: 'Byrne exchanges.' },
      { move: 'Nxd1', eval: '-7.8', comment: 'Fischer recaptures, leaving him with an extra rook, two bishops, and a pawn.' },
      { move: 'h3', eval: '-8.5', comment: 'Creating escape room.' },
      { move: 'Rxa2', eval: '-9.0', comment: 'Grabbing the 7th rank.' },
      { move: 'Kh2', eval: '-9.0', comment: 'King safety.' },
      { move: 'Nxf2', eval: '-9.5', comment: 'Capturing f2.' },
      { move: 'Re1', eval: '-10.0', comment: 'Controlling e-file.' },
      { move: 'Rxe1', eval: '-11.0', comment: 'Exchanging rooks.' },
      { move: 'Qd8+', eval: '-11.0', comment: 'Desperation check.' },
      { move: 'Bf8', eval: '-11.5', comment: 'Blocks easily.' },
      { move: 'Nxe1', eval: '-12.0', comment: 'White recaptures.' },
      { move: 'Bd5', eval: '-12.5', comment: 'Fischer activates the light-squared bishop.' },
      { move: 'Nf3', eval: '-13.0', comment: 'Knight develops.' },
      { move: 'Ne4', eval: '-13.5', comment: 'Fischer centralizes knight.' },
      { move: 'Qb8', eval: '-14.0', comment: 'Attacking b7.' },
      { move: 'b5', eval: '-14.5', comment: 'Passed pawn advances.' },
      { move: 'h4', eval: '-15.0', comment: 'Pawn push.' },
      { move: 'h5', eval: '-15.5', comment: 'Blocks.' },
      { move: 'Ne5', eval: '-16.0', comment: 'Threatening checks.' },
      { move: 'Kg7', eval: '-16.5', comment: 'King out of danger.' },
      { move: 'Kg1', eval: '-17.0', comment: 'Passive king.' },
      { move: 'Bc5+', eval: '-18.0', comment: 'Checks.' },
      { move: 'Kf1', eval: '-18.0', comment: 'Forced.' },
      { move: 'Ng3+', eval: '-19.5', comment: 'Forced king to e1.' },
      { move: 'Ke1', eval: '-19.5', comment: 'Forced.' },
      { move: 'Bb4+', eval: '-21.0', comment: 'Pinning king.' },
      { move: 'Kd1', eval: '-21.0', comment: 'Forced.' },
      { move: 'Bb3+', eval: '-25.0', comment: 'Checks.' },
      { move: 'Kc1', eval: '-25.0', comment: 'Forced.' },
      { move: 'Ne2+', eval: '-30.0', comment: 'Knight check.' },
      { move: 'Kb1', eval: '-30.0', comment: 'Forced.' },
      { move: 'Nc3+', eval: '-35.0', comment: 'Double check.' },
      { move: 'Kc1', eval: '-35.0', comment: 'Forced.' },
      { move: 'Rc2#', eval: '-Mate', comment: 'Checkmate! A beautiful checkmate finish.' }
    ]
  },
  {
    id: 'kasparov_topalov',
    white: 'Garry Kasparov',
    black: 'Veselin Topalov',
    event: 'Wijk aan Zee',
    date: '1999',
    result: '1-0',
    description: 'Kasparov\'s Immortal. A brilliant rook sacrifice initiates a direct king hunt across the board in one of the most calculated attacking games of all time.',
    initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    moves: [
      { move: 'e4', eval: '+0.2', comment: 'Kasparov opens with king pawn.' },
      { move: 'd6', eval: '+0.2', comment: 'Pirc Defense.' },
      { move: 'd4', eval: '+0.3', comment: 'White claims the center.' },
      { move: 'Nf6', eval: '+0.3', comment: 'Black attacks e4.' },
      { move: 'Nc3', eval: '+0.3', comment: 'Developing Nc3.' },
      { move: 'g6', eval: '+0.4', comment: 'Prepares fianchetto.' },
      { move: 'Be3', eval: '+0.4', comment: 'Byrne system / 150 attack setup.' },
      { move: 'Bg7', eval: '+0.4', comment: 'Developing bishop.' },
      { move: 'Qd2', eval: '+0.5', comment: 'Preparing Qd2 and Bh6 trade.' },
      { move: 'c6', eval: '+0.5', comment: 'Solidifying.' },
      { move: 'f3', eval: '+0.6', comment: 'Support center, prepare g4 storm.' },
      { move: 'b5', eval: '+0.6', comment: 'Queenside space grab.' },
      { move: 'Nge2', eval: '+0.5', comment: 'Developing knight.' },
      { move: 'Nbd7', eval: '+0.6', comment: 'Knight supports.' },
      { move: 'Bh6', eval: '+0.7', comment: 'Offering bishop trade.' },
      { move: 'Bxh6', eval: '+0.7', comment: 'Black accepts.' },
      { move: 'Qxh6', eval: '+0.7', comment: 'Recapture queen.' },
      { move: 'Bb7', eval: '+0.7', comment: 'Fianchetto.' },
      { move: 'a3', eval: '+0.8', comment: 'Restricting b4 push.' },
      { move: 'e5', eval: '+0.8', comment: 'Striking center.' },
      { move: 'O-O-O', eval: '+0.9', comment: 'Castling queenside.' },
      { move: 'Qe7', eval: '+0.9', comment: 'Ready to castle queenside.' },
      { move: 'Kb1', eval: '+1.0', comment: 'Prophylactic king move.' },
      { move: 'a6', eval: '+1.0', comment: 'Quiet pawn move.' },
      { move: 'Nc1', eval: '+1.2', comment: 'Knight heads to b3/a5.' },
      { move: 'O-O-O', eval: '+1.2', comment: 'Castled.' },
      { move: 'Nb3', eval: '+1.3', comment: 'Targeting a5.' },
      { move: 'exd4', eval: '+1.3', comment: 'Black opens file.' },
      { move: 'Rxd4', eval: '+1.4', comment: 'Active rook recapture.' },
      { move: 'c5', eval: '+1.2', comment: 'Chasing rook.' },
      { move: 'Rd1', eval: '+1.3', comment: 'Rook retreats.' },
      { move: 'Nb6', eval: '+1.3', comment: 'Developing.' },
      { move: 'g3', eval: '+1.5', comment: 'Solidifying f4.' },
      { move: 'Kb8', eval: '+1.5', comment: 'King safety.' },
      { move: 'Na5', eval: '+1.7', comment: 'Outpost knight on a5.' },
      { move: 'Ba8', eval: '+1.7', comment: 'Bishop retreats.' },
      { move: 'Bh3', eval: '+1.9', comment: 'Taking control of active diagonal.' },
      { move: 'd5', eval: '+1.8', comment: 'Strike in center.' },
      { move: 'Qf4+', eval: '+2.0', comment: 'White checks king.' },
      { move: 'Ka7', eval: '+2.0', comment: 'Forced.' },
      { move: 'Rhe1', eval: '+2.2', comment: 'All white pieces coordinate.' },
      { move: 'd4', eval: '+2.2', comment: 'Advancing pawn.' },
      { move: 'Nd5', eval: '+2.4', comment: 'Knight outpost.' },
      { move: 'Nbxd5', eval: '+2.4', comment: 'Trades.' },
      { move: 'exd5', eval: '+2.5', comment: 'Recapture.' },
      { move: 'Qd6', eval: '+2.5', comment: 'Attacking d5.' },
      { move: 'Rxd4', eval: '+4.5', idea: 'Rook Sacrifice', motif: 'Brilliency', comment: 'The legendary rook sacrifice! Kasparov gives up his rook for a historic king hunt.' },
      { move: 'cxd4', eval: '+4.5', comment: 'Accepting the sacrifice.' },
      { move: 'Re7+', eval: '+4.8', comment: 'Rook invades the 7th rank with check.' },
      { move: 'Kb6', eval: '+4.8', comment: 'King escapes.' },
      { move: 'Qxd4+', eval: '+5.0', comment: 'Queen check.' },
      { move: 'Kxa5', eval: '+5.0', comment: 'King forced further out.' },
      { move: 'b4+', eval: '+5.2', comment: 'Striking pawn check.' },
      { move: 'Kxa4', eval: '+5.2', comment: 'King has walked all the way to a4!' },
      { move: 'Qc3', eval: '+5.8', comment: 'Setting up mating nets.' },
      { move: 'Qxd5', eval: '+5.8', comment: 'Black tries to defend.' },
      { move: 'Ra7', eval: '+6.2', comment: 'Threatening mating blow.' },
      { move: 'Bb7', eval: '+6.2', comment: 'Black tries to block.' },
      { move: 'Rxb7', eval: '+6.8', comment: 'Rook capture.' },
      { move: 'Qc4', eval: '+6.8', comment: 'Desperation.' },
      { move: 'Qxf6', eval: '+8.0', comment: 'Winning more pawns.' },
      { move: 'Kxa3', eval: '+8.0', comment: 'King grabs pawn.' },
      { move: 'Qxa6+', eval: '+9.5', comment: 'Checks.' },
      { move: 'Kxb4', eval: '+9.5', comment: 'March continues.' },
      { move: 'c3+', eval: '+12.0', comment: 'Forced check.' },
      { move: 'Kxc3', eval: '+12.0', comment: 'Forced.' },
      { move: 'Qa1+', eval: '+15.0', comment: 'Checkmate sequence.' },
      { move: 'Kd2', eval: '+15.0', comment: 'King retreats.' },
      { move: 'Qb2+', eval: '+18.0', comment: 'Check.' },
      { move: 'Kd1', eval: '+18.0', comment: 'Forced.' },
      { move: 'Bf1', eval: '+20.0', comment: 'Bishop finishes the net.' },
      { move: 'Rd2', eval: '+20.0', comment: 'Desperation.' },
      { move: 'Rd7', eval: '+25.0', comment: 'Rook block check.' },
      { move: 'Rxd7', eval: '+25.0', comment: 'Capturing.' },
      { move: 'Bxc4', eval: '+30.0', comment: 'Winning the queen.' },
      { move: 'bxc4', eval: '+30.0', comment: 'Recapture.' },
      { move: 'Qxh8', eval: '+40.0', comment: 'Kasparov is completely winning.' },
      { move: 'Rd3', eval: '+40.0', comment: 'Last threats.' },
      { move: 'Qa8', eval: '+50.0', comment: 'Queen checks.' },
      { move: 'c3', eval: '+50.0', comment: 'Pawn push.' },
      { move: 'Qa4+', eval: '+Mate', comment: 'Mate threat.' },
      { move: 'Ke1', eval: '+Mate', comment: 'King retreats.' },
      { move: 'f4', eval: '+Mate', comment: 'Black resigns.' }
    ]
  },
  {
    id: 'carlsen_anand',
    white: 'Magnus Carlsen',
    black: 'Viswanathan Anand',
    event: 'World Championship',
    date: '2013',
    result: '1-0',
    description: 'Carlsen secures a strategic bind in the World Championship, demonstrating his superior positional squeezing ability and relentless technical precision.',
    initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    moves: [
      { move: 'Nf3', eval: '+0.1', comment: 'Carlsen opens flexibly.' },
      { move: 'd5', eval: '+0.1', comment: 'Anand claims center.' },
      { move: 'g3', eval: '+0.2', comment: 'Kingside fianchetto.' },
      { move: 'g6', eval: '+0.2', comment: 'Symmetrical fianchetto.' },
      { move: 'Bg2', eval: '+0.2', comment: 'Bishop developed.' },
      { move: 'Bg7', eval: '+0.2', comment: 'Bishop developed.' },
      { move: 'd4', eval: '+0.3', comment: 'Staking center claim.' },
      { move: 'c6', eval: '+0.3', comment: 'Solidifying d5.' },
      { move: 'O-O', eval: '+0.3', comment: 'Castles.' },
      { move: 'Nf6', eval: '+0.3', comment: 'Developing knight.' },
      { move: 'b3', eval: '+0.4', comment: 'Preparing Bb2.' },
      { move: 'O-O', eval: '+0.4', comment: 'Castled.' },
      { move: 'Bb2', eval: '+0.4', comment: 'Bishop developed.' },
      { move: 'Bf5', eval: '+0.4', comment: 'Active bishop.' },
      { move: 'c4', eval: '+0.5', comment: 'Challenging d5.' },
      { move: 'Nbd7', eval: '+0.5', comment: 'Knight develops.' },
      { move: 'Nc3', eval: '+0.6', comment: 'Knight develops.' },
      { move: 'dxc4', eval: '+0.4', comment: 'Releasing center tension.' },
      { move: 'bxc4', eval: '+0.4', comment: 'Recapture.' },
      { move: 'Nb6', eval: '+0.3', comment: 'Targeting c4.' },
      { move: 'c5', eval: '+0.5', comment: 'Carlsen pushes forward, claiming space.' },
      { move: 'Nc4', eval: '+0.4', comment: 'Knight outpost on c4.' },
      { move: 'Bc1', eval: '+0.5', comment: 'Retreating bishop.' },
      { move: 'Nd5', eval: '+0.4', comment: 'Centralizing knight.' },
      { move: 'Qb3', eval: '+0.6', comment: 'Active queen development.' },
      { move: 'Na5', eval: '+0.4', comment: 'Attacking queen.' },
      { move: 'Qa3', eval: '+0.6', comment: 'Keeping pressure.' },
      { move: 'Nc4', eval: '+0.4', comment: 'Knight maneuvers.' },
      { move: 'Qa4', eval: '+0.6', comment: 'Threatening.' },
      { move: 'Nd6', eval: '+0.5', comment: 'Retreating knight.' },
      { move: 'cxd6', eval: '+0.6', comment: 'Creating passed pawn imbalance.' },
      { move: 'exd6', eval: '+0.6', comment: 'Recapture.' },
      { move: 'Qc2', eval: '+0.7', comment: 'Active queen file.' },
      { move: 'Re8', eval: '+0.7', comment: 'Controlling e-file.' },
      { move: 'Rd1', eval: '+0.8', comment: 'Defending.' },
      { move: 'Nf6', eval: '+0.8', comment: 'Knight develops.' },
      { move: 'Bf4', eval: '+0.9', comment: 'Active bishop.' },
      { move: 'Nh5', eval: '+0.9', comment: 'Chasing bishop.' },
      { move: 'Bd2', eval: '+1.0', comment: 'Retreat.' },
      { move: 'Re6', eval: '+1.0', comment: 'Rook lift.' },
      { move: 'e4', eval: '+1.2', comment: 'Carlsen breaks in the center!' },
      { move: 'Bd7', eval: '+1.2', comment: 'Developing.' },
      { move: 'a4', eval: '+1.3', comment: 'Queenside space expansion.' },
      { move: 'Qe7', eval: '+1.3', comment: 'Connecting rooks.' },
      { move: 'a5', eval: '+1.5', comment: 'Restricting Black.' },
      { move: 'f6', eval: '+1.5', comment: 'Solidifying.' },
      { move: 'Rab1', eval: '+1.8', comment: 'Invading open file.' },
      { move: 'Rae8', eval: '+1.8', comment: 'Doubling rooks.' },
      { move: 'Qc1', eval: '+2.0', comment: 'Maneuvering.' },
      { move: 'Kh8', eval: '+2.0', comment: 'King safety.' },
      { move: 'b4', eval: '+2.2', comment: 'Space push.' },
      { move: 'Qf8', eval: '+2.2', comment: 'Queen retreats.' },
      { move: 'Bc3', eval: '+2.5', comment: 'Coordinates.' },
      { move: 'Be7', eval: '+2.5', comment: 'Bishop adjusts.' },
      { move: 'Nd2', eval: '+2.8', comment: 'Heads to c4.' },
      { move: 'Bf8', eval: '+2.8', comment: 'Defensive adjustments.' },
      { move: 'Nb3', eval: '+3.0', comment: 'Active knight.' },
      { move: 'd5', eval: '+3.2', comment: 'Center strike.' },
      { move: 'e5', eval: '+3.5', comment: 'Passed pawn block.' },
      { move: 'fxe5', eval: '+3.5', comment: 'Captures.' },
      { move: 'dxe5', eval: '+3.8', comment: 'Recapture.' },
      { move: 'Bc8', eval: '+4.0', comment: 'Retreats.' },
      { move: 'Na4', eval: '+4.8', comment: 'Complete squeeze of Black\'s position.' }
    ]
  },
  {
    id: 'tal_larsen',
    white: 'Mikhail Tal',
    black: 'Bent Larsen',
    event: 'Candidates Match',
    date: '1965',
    result: '1-0',
    description: 'The Magician of Riga strikes again. Tal launches a fierce kingside attack with speculating sacrifices, creating an chaotic double-edged tactical battle.',
    initialFen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    moves: [
      { move: 'e4', eval: '+0.2', comment: 'Tal opens e4.' },
      { move: 'c5', eval: '+0.2', comment: 'Sicilian Defense.' },
      { move: 'Nf3', eval: '+0.3', comment: 'Developing.' },
      { move: 'Nc6', eval: '+0.3', comment: 'Developing Nc6.' },
      { move: 'd4', eval: '+0.3', comment: 'Center breakthrough.' },
      { move: 'cxd4', eval: '+0.3', comment: 'Capture.' },
      { move: 'Nxd4', eval: '+0.3', comment: 'Recapture.' },
      { move: 'e6', eval: '+0.4', comment: 'Four Knights setup.' },
      { move: 'Nc3', eval: '+0.4', comment: 'Developing Nc3.' },
      { move: 'd6', eval: '+0.4', comment: 'Flexible structures.' },
      { move: 'Be3', eval: '+0.5', comment: 'Active bishop.' },
      { move: 'Nf6', eval: '+0.5', comment: 'Knight attacks.' },
      { move: 'f3', eval: '+0.6', comment: 'Defending.' },
      { move: 'Be7', eval: '+0.6', comment: 'Bishop develops.' },
      { move: 'Qd2', eval: '+0.7', comment: 'Preparing castling.' },
      { move: 'O-O', eval: '+0.7', comment: 'Castling kingside.' },
      { move: 'O-O-O', eval: '+0.8', comment: 'Tal castles queenside.' },
      { move: 'a6', eval: '+0.8', comment: 'Space check.' },
      { move: 'g4', eval: '+1.0', comment: 'Typical Tal pawn storm!' },
      { move: 'Nxd4', eval: '+1.0', comment: 'Trades.' },
      { move: 'Bxd4', eval: '+1.1', comment: 'Recapture.' },
      { move: 'b5', eval: '+1.0', comment: 'Counterplay on queenside.' },
      { move: 'g5', eval: '+1.2', comment: 'Chasing knight.' },
      { move: 'Nd7', eval: '+1.2', comment: 'Retreat.' },
      { move: 'h4', eval: '+1.3', comment: 'Support push.' },
      { move: 'b4', eval: '+1.0', comment: 'Chasing Nc3.' },
      { move: 'Na4', eval: '+1.2', comment: 'Knight outpost.' },
      { move: 'Bb7', eval: '+1.2', comment: 'Fianchetto.' },
      { move: 'Qxb4', eval: '+1.3', comment: 'Tal grabs the pawn.' },
      { move: 'Bc6', eval: '+1.2', comment: 'Targeting.' },
      { move: 'b3', eval: '+1.3', comment: 'Solidifying.' },
      { move: 'Bxa4', eval: '+1.2', comment: 'Capture.' },
      { move: 'bxa4', eval: '+1.3', comment: 'Recapture.' },
      { move: 'd5', eval: '+1.2', comment: 'Striking center.' },
      { move: 'Bd3', eval: '+1.3', comment: 'Developing.' },
      { move: 'dxe4', eval: '+1.2', comment: 'Capture.' },
      { move: 'fxe4', eval: '+1.3', comment: 'Recapture.' },
      { move: 'e5', eval: '+1.2', comment: 'Passed pawn block.' },
      { move: 'Be3', eval: '+1.3', comment: 'Retreat.' },
      { move: 'Bc5', eval: '+1.2', comment: 'Exchange offer.' },
      { move: 'Bxc5', eval: '+1.3', comment: 'Exchanged.' },
      { move: 'Nxc5', eval: '+1.3', comment: 'Knight recapture.' },
      { move: 'h5', eval: '+1.5', comment: 'Storm continues.' },
      { move: 'Nxa4', eval: '+1.5', comment: 'Larsen grabs.' },
      { move: 'g6', eval: '+2.5', comment: 'Tal sacrifices pawns to smash the king safety!' },
      { move: 'fxg6', eval: '+2.5', comment: 'Accepts.' },
      { move: 'hxg6', eval: '+2.8', comment: 'Exchanges.' },
      { move: 'h6', eval: '+2.8', comment: 'Larsen defends.' },
      { move: 'Rdg1', eval: '+3.5', comment: 'Controlling open line.' },
      { move: 'Qe7', eval: '+3.5', comment: 'Coordinates.' },
      { move: 'Bc4+', eval: '+4.5', comment: 'Check!' },
      { move: 'Kh8', eval: '+4.5', comment: 'Forced.' },
      { move: 'Rh5', eval: '+4.8', comment: 'Rook lift sacrifice!' },
      { move: 'Nc5', eval: '+4.8', comment: 'Knight coordinates.' },
      { move: 'Rxe5', eval: '+5.5', comment: 'Audacious capture!' },
      { move: 'Qf6', eval: '+5.5', comment: 'Targeting.' },
      { move: 'Rxc5', eval: '+6.2', comment: 'Winning.' },
      { move: 'Qxg6', eval: '+6.2', comment: 'Grabbing.' },
      { move: 'Rc7', eval: '+7.5', comment: 'Devastating infiltration.' }
    ]
  }
];

export function getMasterGame(id: string) {
  return MASTER_GAMES.find(g => g.id === id);
}
